#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hookshot.Client.Resource", IsApplication=true)]

namespace Hookshot.Client
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
    public partial class Resource
    {
        
        static Resource()
        {
            global::Android.Runtime.ResourceIdManager.UpdateIdValues();
        }
        
        public static void UpdateIdValues()
        {
        }
        
        public partial class Attribute
        {
            
            static Attribute()
            {
                global::Android.Runtime.ResourceIdManager.UpdateIdValues();
            }
            
            private Attribute()
            {
            }
        }
        
        public partial class Drawable
        {
            
            // aapt resource value: 0x7f020000
            public const int Drive = 2130837504;
            
            // aapt resource value: 0x7f020001
            public const int File = 2130837505;
            
            // aapt resource value: 0x7f020002
            public const int Folder = 2130837506;
            
            // aapt resource value: 0x7f020003
            public const int Icon = 2130837507;
            
            // aapt resource value: 0x7f020004
            public const int Preparing = 2130837508;
            
            // aapt resource value: 0x7f020005
            public const int Saved = 2130837509;
            
            static Drawable()
            {
                global::Android.Runtime.ResourceIdManager.UpdateIdValues();
            }
            
            private Drawable()
            {
            }
        }
        
        public partial class Id
        {
            
            // aapt resource value: 0x7f050008
            public const int AddressEdit = 2131034120;
            
            // aapt resource value: 0x7f050007
            public const int AddressText = 2131034119;
            
            // aapt resource value: 0x7f050000
            public const int FileBrowserListView = 2131034112;
            
            // aapt resource value: 0x7f050001
            public const int MainListView = 2131034113;
            
            // aapt resource value: 0x7f050006
            public const int NameEdit = 2131034118;
            
            // aapt resource value: 0x7f050005
            public const int NameText = 2131034117;
            
            // aapt resource value: 0x7f050002
            public const int PerformanceListView = 2131034114;
            
            // aapt resource value: 0x7f050003
            public const int ProcessesListView = 2131034115;
            
            // aapt resource value: 0x7f05000a
            public const int ScreenImageView = 2131034122;
            
            // aapt resource value: 0x7f050009
            public const int ServerInfoListView = 2131034121;
            
            // aapt resource value: 0x7f050004
            public const int ServerListView = 2131034116;
            
            // aapt resource value: 0x7f05000c
            public const int SpeakEditText = 2131034124;
            
            // aapt resource value: 0x7f05000e
            public const int SpeakRateSeek = 2131034126;
            
            // aapt resource value: 0x7f05000d
            public const int SpeakRateText = 2131034125;
            
            // aapt resource value: 0x7f05000b
            public const int SpeakText = 2131034123;
            
            // aapt resource value: 0x7f050010
            public const int SpeakVolumeSeek = 2131034128;
            
            // aapt resource value: 0x7f05000f
            public const int SpeakVolumeText = 2131034127;
            
            // aapt resource value: 0x7f050012
            public const int VolumeSeek = 2131034130;
            
            // aapt resource value: 0x7f050011
            public const int VolumeText = 2131034129;
            
            static Id()
            {
                global::Android.Runtime.ResourceIdManager.UpdateIdValues();
            }
            
            private Id()
            {
            }
        }
        
        public partial class Layout
        {
            
            // aapt resource value: 0x7f030000
            public const int FileBrowser = 2130903040;
            
            // aapt resource value: 0x7f030001
            public const int Main = 2130903041;
            
            // aapt resource value: 0x7f030002
            public const int Performance = 2130903042;
            
            // aapt resource value: 0x7f030003
            public const int Processes = 2130903043;
            
            // aapt resource value: 0x7f030004
            public const int Server = 2130903044;
            
            // aapt resource value: 0x7f030005
            public const int ServerEditor = 2130903045;
            
            // aapt resource value: 0x7f030006
            public const int ServerInfo = 2130903046;
            
            // aapt resource value: 0x7f030007
            public const int ServerScreen = 2130903047;
            
            // aapt resource value: 0x7f030008
            public const int SpeakDialog = 2130903048;
            
            // aapt resource value: 0x7f030009
            public const int VolumeDialog = 2130903049;
            
            static Layout()
            {
                global::Android.Runtime.ResourceIdManager.UpdateIdValues();
            }
            
            private Layout()
            {
            }
        }
        
        public partial class String
        {
            
            // aapt resource value: 0x7f040001
            public const int ApplicationName = 2130968577;
            
            // aapt resource value: 0x7f040000
            public const int Hello = 2130968576;
            
            static String()
            {
                global::Android.Runtime.ResourceIdManager.UpdateIdValues();
            }
            
            private String()
            {
            }
        }
    }
}
#pragma warning restore 1591
